; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
lib_deps =
    https://github.com/ThingPulse/esp8266-oled-ssd1306.git
    https://github.com/arduino-libraries/Servo.git
    https://github.com/blinker-iot/blinker-library.git
    https://github.com/arduino-libraries/NTPClient.git
    https://github.com/bogde/HX711.git
    https://github.com/mathertel/OneButton.git

monitor_speed = 115200